/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlsv;

import javax.swing.JOptionPane;
import qlsv.loginedUser;
/**
 *
 * @author Admin
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    private loginedUser user = null ;
    public menu(){
        initComponents();
    }
    public menu(loginedUser user) {
        this.user = new loginedUser(user);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txttenchucnang = new javax.swing.JLabel();
        btkhht = new javax.swing.JButton();
        btDOIMATKHAU = new javax.swing.JButton();
        btthongtincovan = new javax.swing.JButton();
        btquanlydiem = new javax.swing.JButton();
        btcosovatchat = new javax.swing.JButton();
        btdanhgiarenluyen = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btdangxuat = new javax.swing.JButton();
        btthoatungdung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Sinh Viên");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 255, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("CÁC CHỨC NĂNG HỆ THỐNG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        txttenchucnang.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N

        btkhht.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Capture2.PNG"))); // NOI18N
        btkhht.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btkhhtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btkhhtMouseExited(evt);
            }
        });
        btkhht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkhhtActionPerformed(evt);
            }
        });

        btDOIMATKHAU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Capture6.PNG"))); // NOI18N
        btDOIMATKHAU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btDOIMATKHAUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btDOIMATKHAUMouseExited(evt);
            }
        });
        btDOIMATKHAU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDOIMATKHAUActionPerformed(evt);
            }
        });

        btthongtincovan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Capture5.PNG"))); // NOI18N
        btthongtincovan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btthongtincovanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btthongtincovanMouseExited(evt);
            }
        });
        btthongtincovan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthongtincovanActionPerformed(evt);
            }
        });

        btquanlydiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Capture9.PNG"))); // NOI18N
        btquanlydiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btquanlydiemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btquanlydiemMouseExited(evt);
            }
        });
        btquanlydiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btquanlydiemActionPerformed(evt);
            }
        });

        btcosovatchat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Capture8.PNG"))); // NOI18N
        btcosovatchat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btcosovatchatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btcosovatchatMouseExited(evt);
            }
        });
        btcosovatchat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcosovatchatActionPerformed(evt);
            }
        });

        btdanhgiarenluyen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Capture7.PNG"))); // NOI18N
        btdanhgiarenluyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btdanhgiarenluyenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btdanhgiarenluyenMouseExited(evt);
            }
        });
        btdanhgiarenluyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdanhgiarenluyenActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 255, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("LẬP TRÌNH JAVA CT276 _HUỲNH TẤN HUY B1906674");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        btdangxuat.setText("ĐĂNG XUẤT");
        btdangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdangxuatActionPerformed(evt);
            }
        });

        btthoatungdung.setText("THOÁT");
        btthoatungdung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthoatungdungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txttenchucnang, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btkhht, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btDOIMATKHAU, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(74, 74, 74)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btcosovatchat, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btquanlydiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btthongtincovan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btdanhgiarenluyen, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(9, 9, 9))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btdangxuat)
                        .addGap(88, 88, 88)
                        .addComponent(btthoatungdung, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(txttenchucnang, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btquanlydiem, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btthongtincovan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btkhht, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btdanhgiarenluyen, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btcosovatchat, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btDOIMATKHAU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btdangxuat)
                    .addComponent(btthoatungdung))
                .addGap(37, 37, 37)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btquanlydiemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btquanlydiemMouseEntered
        // TODO add your handling code here:
        txttenchucnang.setText(" QUẢN LÝ ĐIỂM SINH VIÊN");
    }//GEN-LAST:event_btquanlydiemMouseEntered

    private void btquanlydiemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btquanlydiemMouseExited
        // TODO add your handling code here:
        txttenchucnang.setText(" ");
    }//GEN-LAST:event_btquanlydiemMouseExited

    private void btthongtincovanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btthongtincovanMouseEntered
        // TODO add your handling code here:
        txttenchucnang.setText("        THÔNG TIN CỐ VẤN");
    }//GEN-LAST:event_btthongtincovanMouseEntered

    private void btthongtincovanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btthongtincovanMouseExited
        // TODO add your handling code here:
        txttenchucnang.setText(" ");
    }//GEN-LAST:event_btthongtincovanMouseExited

    private void btkhhtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btkhhtMouseEntered
        // TODO add your handling code here:
        txttenchucnang.setText("      KẾ HOẠCH HỌC TẬP");
    }//GEN-LAST:event_btkhhtMouseEntered

    private void btkhhtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btkhhtMouseExited
        // TODO add your handling code here:
        txttenchucnang.setText(" ");
    }//GEN-LAST:event_btkhhtMouseExited

    private void btDOIMATKHAUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDOIMATKHAUMouseEntered
        // TODO add your handling code here:
        txttenchucnang.setText("          ĐỔI MẬT KHẨU");
    }//GEN-LAST:event_btDOIMATKHAUMouseEntered

    private void btDOIMATKHAUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDOIMATKHAUMouseExited
        // TODO add your handling code here:
        txttenchucnang.setText(" ");
    }//GEN-LAST:event_btDOIMATKHAUMouseExited

    private void btcosovatchatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcosovatchatMouseEntered
        // TODO add your handling code here:
        txttenchucnang.setText("          CƠ SỞ HẠ TẦNG");
    }//GEN-LAST:event_btcosovatchatMouseEntered

    private void btcosovatchatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcosovatchatMouseExited
        // TODO add your handling code here:
        txttenchucnang.setText(" ");
    }//GEN-LAST:event_btcosovatchatMouseExited

    private void btdanhgiarenluyenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btdanhgiarenluyenMouseEntered
        // TODO add your handling code here:
        txttenchucnang.setText("      THƯ VIỆN ĐIỆN TỬ");
    }//GEN-LAST:event_btdanhgiarenluyenMouseEntered

    private void btdanhgiarenluyenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btdanhgiarenluyenMouseExited
        // TODO add your handling code here:
        txttenchucnang.setText(" ");
    }//GEN-LAST:event_btdanhgiarenluyenMouseExited

    private void btkhhtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkhhtActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Chức năng đang bảo trì , vui lòng quay lại sau!","Thông báo",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btkhhtActionPerformed

    private void btDOIMATKHAUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDOIMATKHAUActionPerformed
        // TODO add your handling code here:
        doipass passchange = new doipass(user);
        passchange.show();
        dispose();
    }//GEN-LAST:event_btDOIMATKHAUActionPerformed

    private void btcosovatchatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcosovatchatActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Chức năng đang bảo trì , vui lòng quay lại sau!","Thông báo",JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btcosovatchatActionPerformed

    private void btthongtincovanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthongtincovanActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Chức năng đang bảo trì , vui lòng quay lại sau!","Thông báo",JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btthongtincovanActionPerformed

    private void btdanhgiarenluyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdanhgiarenluyenActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Chức năng đang bảo trì , vui lòng quay lại sau!","Thông báo",JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btdanhgiarenluyenActionPerformed

    private void btthoatungdungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthoatungdungActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btthoatungdungActionPerformed
    
    private void btdangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdangxuatActionPerformed
        // TODO add your handling code here:
        Login lg = new Login();
        lg.show();
        dispose();
    }//GEN-LAST:event_btdangxuatActionPerformed

    private void btquanlydiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btquanlydiemActionPerformed
        // TODO add your handling code here:
        QLSinhVien qlsv = new QLSinhVien();
        qlsv.show();
        dispose();
    }//GEN-LAST:event_btquanlydiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDOIMATKHAU;
    private javax.swing.JButton btcosovatchat;
    private javax.swing.JButton btdangxuat;
    private javax.swing.JButton btdanhgiarenluyen;
    private javax.swing.JButton btkhht;
    private javax.swing.JButton btquanlydiem;
    private javax.swing.JButton btthoatungdung;
    private javax.swing.JButton btthongtincovan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txttenchucnang;
    // End of variables declaration//GEN-END:variables
}
